### ISSUE TITLE
no options menu found

### ISSUE THREAD

**Issue by skleene** [Lusito/forget-me-not#101]
I just installed Forget Me Not 1.0.5 in Firefox 60.2.0esr under Debian v9
(Stretch).  I did this to replace selectivecookiedelete, which is no longer
supported.

Forget Me Not shows in Firefox's Extensions page, but I can find no way to
bring up its menu.  I thought that clicking on the flower icon should do
that.  Instead it opens up an empty dashed box that extends to the bottom of
the window.  I can't scroll any lower.

Any idea how to bring up the Forget Me Not menu?  Thanks.

**Comment by Lusito** [comment]
Clicking on the flower icon on the toolbar should bring it up. Not sure why it wouldn't. Have you tried restarting the browser?

**Comment by skleene** [comment]
Thanks.  That worked, so I'm all set.  I hadn't noticed the little flower on the toolbar.  I was clicking on the flower next to the add-on name on Firefox's Extensions page.
________________________________

**Comment by Lusito** [comment]
No problem. Enjoy.
