### ISSUE TITLE
Unable to view cookies contents in Firefox 62 after installing Forget Me Not?

### ISSUE THREAD

**Issue by bendover22** [Lusito/forget-me-not#102]
Unless these are Firefox 62.0.2 x64 Linux behavior changes (not FMN 1.0.5 behavior), with cookies enabled in Fx, only names of cookies are visible in Fx prefs / Cookies / Manage Data.  If there are multiple cookies from one domain, it just shows a number beside the domain.
So there may be no quick way to look at  all cookies & contents from all domains (which isn't good).

Before installing FMN & before updating to Fx 62.0.2, I could see the contents of cookies in the Fx UI.  Has anyone else noticed this?  I might have to uninstall FMN to see if it reverses the issue.

Otherwise, we need some way  to look at cookie contents - a list of cookies, cookie type (white, gray...) and option to show their contents (sometimes)  It doesn't appear possible now with FMN.
Yes - we can look at an individual site / tab to inspect cookies.  I sure wouldn't want to do that on 10 or 20 different tabs w/ different domains.

FYI, the Preview post isn't working.  It'll only let me submit the comment.

**Comment by Lusito** [comment]
Thanks for taking the time to report this, but that's a change in Firefox itself, not FMN.

Extensions can't remove native Firefox UI. When you uninstall FMN, you won't get this feature back. Mozilla just decided it's too complicated for users and removed it.

Give #9 a thumbs up to show your interest in FMN implementing this independently of Firefox.
