### ISSUE TITLE
can't set default behavior to Block

### ISSUE THREAD

**Issue by skleene** [Lusito/forget-me-not#103]
I've installed Forget Me Not (v1.0.5) in Firefox 60.2.1esr running on Debian
v9 (Stretch).  Manual cleanup works, and I've been able to whitelist a site.
I've been unable to set "Behavior if no rule matches" to Block.  Should that
be possible?  The dropdown menu offers Block as a choice, and I see no error
message.  But if I bring up the Rules menu again, it still shows the default
(Forget).  And cookies are allowed to accumulate.  I reset all settings to
the defaults before doing these tests.

I'd like to block cookies from all sites except one.  That worked well for me
with the selectivecookiedelete add-on.  Maybe an alternative in Forget Me Not
is to set the delays to 0.

Any advice?  Thank you.

**Comment by Lusito** [comment]
That should be possible. I wasn't able to reproduce.. I'll see if I can get a virtual box up and running with debian v9 and firefox 60.2.1esr to see if I can reproduce it there.

**Comment by skleene** [comment]
Thank you.  I'll stay tuned.  As I said, it might also work to select Forget and set the delays to 0.
________________________________

**Comment by skleene** [comment]
This problem was fixed when I upgraded from Firefox 60.2.1esr to 60.2.2 esr.  Thanks again.
________________________________

**Comment by Lusito** [comment]
That's very weird. Thanks for the heads up. I will try to keep an open eye on this nevertheless.
