### ISSUE TITLE
forget-me-not or Firefox not removing domain names in cookie manager after tabs closed

### ISSUE THREAD

**Issue by bendover22** [Lusito/forget-me-not#104]
Linux Mint 18.1, Firefox 62.0.2 x64, FMN 1.0.5
I created gray rules for several sites I visited.  
Some I logged into, so assume cookies were set.
In FMN settings, Clean when leaving all instances of a domain: **is checked.**
Under that, Cookies & Local Storage were **both checked.**

Delay in minutes was initially zero; later I tried 1 (I assume 0 is valid - a tooltip indicated it was)?
Neither 0 or 1 time delay worked to delete cookie **names** from Fx Cookie Manager (see below).
Due to Mozilla's infinite wisdom it's hard to know if a listed cookie name contains data.  Still, the names should be deleted when all tabs for a site are closed, if possible.

If that can't be done due to API limitations, there can't be much confidence that cookie data was deleted.  Not w/o jumping through many time costly hoops.

But, FMN isn't removing the cookie name in cookie manager after all tabs for a / some sites were closed (only one tab was open per site) .  Also refreshed Fx Privacy & Security tab.
The cookie names remain, but under Fx cookie mgr >  "clear data" shows 0 bytes under cookies, but shows a few KB under Cached content.

Do **javascript** set cookies **always** show under cookies category (in Fx Cookie Mgr), or possibly under Cached content? 
When I RE-logged in VLC forum, 0 kb data (for cookies) was still shown under Fx cookie mgr > Clear data.  It also should? be showing some data for Github cookies, that allow me to post.
It appears there's nothing working in Fx cookie mgr for stored cookie data, whether  or NOT valid cookies are still set, or  no cookie *data* remains.
Either way,  it always shows 0 under Cookies & Site Data.

On the sites - https://forum.videolan.org/index.php & https://bugzilla.mozilla.org/, using View Page Info > Security, ALSO shows the cookie names remained for the sites AFTER I logged out & closed all their tabs.  Apparently, we can no longer see cookie contents on Page Info, either, after a recent Fx upgrade.

ALSO NOTE: when logged in Github to post this, I looked in Cookie Mgr.  It doesn't show any data for Github's cookie (or any site) under Clear Data.
* Should previous cookie exceptions (copied from a pre-quantum profile) be left under Cookies & Site Data > Exceptions, or will they mess up FMN?
At best, the cookie contents were deleted for the closed tabs, but left the names  under Fx Cookie Mgr.  No one wants to have to verify by other means if cookie data was deleted & just left the name.
I tried viewing cookies.sqlite in DB Browser for SQLite, but didn't show any cookies (I wouldn't say that's conclusive, due to the older version of SQLite browser in Mint's repo).

**Comment by Lusito** [comment]
0 is valid, but gray means clean on browser start. If you want to clean on domain leave, red is your rule.

If you are looking at cookies through the preferences page -> manage data popup, then you'll need to refresh the preferences page before you see changes. This dialog is generally not very helpful. I would suggest to use a cookie listing extension for this until FMN brings its own cookie listing UI (I currently use "cookie quick manager").

Cookies set via JavaScript are normal cookies like any other. What shows as "cached content" is usually "local storage" or "indexed db".

Cookie rules you set in firefox are completely out of reach for FMN. For example, if you tell firefox to clear all cookies except some domains, then FMN can't apply its rules on this.

**Comment by bendover22** [comment]
Thanks for the suggestion & confirming my suspicions about Firefox Cookie Manager.
> If you are looking at cookies through the preferences page...This dialog is generally not very helpful.
That's a huge understatement.

It's currently impossible to use the Fx Cookie Mgr to tell at a glance, is cookie contents were deleted & (for some reason) left the name of an empty cookie under Manage Data button.
The Clear Data info - always showing 0 KB of cookie content, even when you know there are active cookies still set, is also useless.

I guess I will have to use another addon to verify cookies were deleted (at least their content).

**Comment by Lusito** [comment]
I'm assuming this was more of a confusion issue with Firefox. If you still think something is wrong with FMN, please elaborate and we can reopen this.

**Comment by bendover22** [comment]
I honestly don't know where the fault lies.  I **don't think** you should close this issue so fast, if only because the problem still exists & no explanation has been given nor an "official" work around posted where users will see it, for other users looking for the same answers .

I can say that when FMN isn't installed, Firefox deleting cookies (say thru settings in Clear History), it **does not leave cookie names** under "Manage Data."  Nor if I click Clear Data in Fx prefs, when FMN isn't installed.  Normally, that suggests the addon is somehow involved.
Install addon - problem appears.  Uninstall addon - problem disappears.

If your personal solution is to use another cookie monitor, I'd think that should be made easily visible to users - especially the more non-technical ones.

**Comment by Lusito** [comment]
Unless I misunderstand this issue, you only need to refresh the preferences tab after the cleanup has been done.

>I can say that when FMN isn't installed, Firefox deleting cookies (say thru settings in Clear History), it does not leave cookie names under "Manage Data." 

That doesn't have anything to do with FMN being installed or not. Try running the exact same cleanup (the ones from Firefox) when FMN is installed.. you'll see no difference.

FMN has no access to this UI, so I can't tell it to update. The only thing I might be able to do is force a refresh on preferences tabs, but that will cause other issues which are not wanted.

There is nothing good I can do about this. The best we could try is open a bug ticket on bugzilla, so mozilla can fix this, but looking at their track record, it might take years before they get to it (if they even decide to do it at all)
