### ISSUE TITLE
How does FMN deal with tabs opened with one site, then others opened in same tab? 

### ISSUE THREAD

**Issue by bendover22** [Lusito/forget-me-not#106]
In FMN 1.0.5, how does it handle tabs that have several different domains opened in the same tab? 
I noticed a site had a black rule ( a black 'B' on FMN icon).
Then I looked at the FMN log & saw a number of sites had black rules set.

Now I see the reason.  Still not sure it was my doing.
I looked under Define Rules: Behavior if no rule matches.  It was set to Black.
I would've had no reason to do that, although after thinking about it some more, it might be a better choice than having to remember how many / which tabs had a given site opened under them, so you can close every single one.

If a tab was originally opened with one site, then another domain opened in that same tab, does FMN remember that the 1st site was opened (at one point) under that tab; therefore, causing you to have to close the tab to meet the "all instances of a site must be closed" for auto cleaning to take place?

Or does FMN only look at the **current domain** - active under a tab, to determine which tabs must be closed for auto cleaning cookies from site xyz.com?

Many users & I see no reason to allow cookies for all sites, regardless of whether they're deleted if you close all a site's tabs. They're still cookies that are usually only useful to the site. 
 If I were 100% confident that FMN or any quantum cookie mgr was working correctly, it might be a bit different.   
Unless I login or it's a "special" site, I rarely need to allow cookies.  If it's a non-special site, that lots of other sites offer the same thing, if it won't work w/o cookies, I just close it & go to another on the list.

A fairly popular? theory is that Mozilla intentionally made it harder to generally block cookies AND allow them only for select sites, in an easy fashion - for a particular rea$on.

**Comment by Lusito** [comment]
- Only the domain which is visible in the url-bar is used to detect the rule shown in the toolbar icon. Nothing else.
- The log shows all domains that changed cookies. Even the ones that have never been in the url-bar. This is so you can easily see where you might need to create or change rules to make a website work as expected.

>Behavior if no rule matches. It was set to Black.

The default is red. I never change this with code, so you must have (accidentally?) changed this somehow.

>does FMN remember that the 1st site was opened (at one point) under that tab

No, for each tab, FMN rememberst the currently active domain (what you see in the url-bar).
There is one exception: During navigation (i.e. when you had google.com in tab A and entered yahoo.com into the url-bar, it takes some time until the switch actually happens.. during that time, FMN will know both google.com and yahoo.com. Once the navigation is complete, only yahoo.com will be known.
