### ISSUE TITLE
Feature enhancement - more choices under "Add Rule" than White or Gray

### ISSUE THREAD

**Issue by bendover22** [Lusito/forget-me-not#107]
Not sure if there's a reason this doesn't  exist, but for individual sites, clicking "Add Rule" 
 the only choices are White (hit enter) or Gray (hit Shft + Enter).
The Red Rule should be added under the "per site" Rules button.  There's a big group of "We only want a site's cookies to remain for the _shortest time possible_ (like Google.anything, under forced conditions).   And, we **don't want** to allow cookies on all sites by default.

The other option, as in the legacy Cookie Monster, is set a Red Rule, allowing temporary cookies on the site, but don't save an exception for the site, and doesn't wait till browser closes (or restarts) to auto clean cookies.   The default cookie behavior could be set to black (close to block cookies by default).  

Red rule isn't available under the Add Rule button but if you add a white or gray rule, THEN you can change those to Red (Forget). Then if the tab(s) for the site are closed, it cleans cookies  immediately, **instead of** persisting all day, before closing the browser.

**Comment by Lusito** [comment]
As you said, you can change the rule after you created it. There just is no convenience method for it as of now. But there will be when #67 is done (it's work in progress).

**Comment by bendover22** [comment]
Did you mean, "there is just no convenient method [_to add another option(s) for red or black rules_] to the drop box when clicking "add rule" button?
I can't imagine why it would be difficult to slightly enlarge the space of the current line,

> "Press enter to add as white rule, shift+enter to add as gray rule"

 & enlarge the container a few px to include one extra line.  Doesn't get much simpler.  

Why close this issue, unless another open issue includes exactly what I outlined (in general).
 I didn't specify it should be done an exact way, just that options to add the other rules on per site should be as easy & the same method as white & gray.  

Forcing  average-to-non-techy users to discover & use a totally different method  to add the other rules and not complain in Reviews  seems illogical.  

How long do would it take to sort through & decide on a UI make-over style, then finish it?
If a few days, then forget my suggestion.  I think it'll be _much_ longer, in which case enlarging the box & adding one more line seems more logical.

**Comment by Lusito** [comment]
As a user, you can change the rules after adding them, so it's just a little inconvenient.
I'm not gonna publish another version before the UI change is complete unless there are security issues.
The UI change will include an easy way to select the rule type upon creation.
