### ISSUE TITLE
Web Translator shows red bar for Lower Sorbian translation

### ISSUE THREAD

**Issue by milupo** [Lusito/forget-me-not#113]
Hi Lusito,

there is a small issue. I've already translated Forget Me Not 1.0.5 into Lower Sorbian in September and sent the translation to Github here: See https://github.com/Lusito/forget-me-not/issues/94

But, Web Translator shows the red bar next to some text, probably thinking that the text is fuzzy. Is it really?

Thanks,
Michael

**Comment by Lusito** [comment]
Sorry, that was my mistake. I made an error applying your changes. You can ignore the red bar on this field for now. With the upcoming UI rework, the editor will glow up like a christmas tree anyway, so if it's okay with you, I'd leave this unchanged until the new UI code is online to be translated.

**Comment by milupo** [comment]
OK, thank you Lusito, no problem.
