### ISSUE TITLE
Blacklist to Specifically Delete Cookies

### ISSUE THREAD

**Issue by tanabi** [Lusito/forget-me-not#12]
Hey there;

I used to use an extension to delete cookies from specific domains on browser close.  I've been trying to find a replacement since the firefox update.  For the most part, I want to default to keeping cookies, but there's certain domains (I'm looking at you, Google and Dropbox) where I DO NOT want to auto-login but they do not provide a means to logout on browser exit.

Your extension is the recommended replacement and it's pretty close ... is it possible to blacklist certain domains and leave the rest?  So basically, when leaving all instances of a domain, delete if its on the blacklist.  The black list would operate no matter what the other settings are ... so in my case, I would leave the "clean when leaving all instances of a domain" unchecked but black list the things I really don't want on there.

**Comment by Lusito** [comment]
Hi Tanabi, Thanks for the feedback.
Currently, it is not possible. I will consider adding this in the future though.

**Comment by Lusito** [comment]
Just wondering.. if you want to enable all but a few specific domains, have you considered using the normal cookie settings?
You can change it to always allow cookies, but never from the specified domains. It might not be as comfortable to edit, but you seem to only care about very few domains, which seems like it would be an acceptable alternative.

In case you can't find it:
- Open options, search for cookie
- Change the history dropdown to custom settings
- Check "Accept cookies from websites" and create exceptions for the websites you want to block.

**Comment by tanabi** [comment]
Hi!  Thanks for your suggestion.  Unfortunately, I don't want to *block* cookies, I just want them gone when I close the tab.

Here's my use case: I log into dropbox, and dropbox does not give me the option to use a session cookie -- it sets a permanent cookie, and I'm logged in forever.  I have sensitive stuff in dropbox, I want it to log me out every time.  So I want the cookie gone when I close the tab, but I do want to be able to log in (so I don't want to block it altogether).

Same with google, except google is worse.  You can never 100% log out of google; you "log out" but it still remembers your user.  I want those cookies gone when I close all my google tabs.

Anyway, consider the feature... I'll look at the code and if its something I feel like I can add, I can always fork and give you a pull request if you like the work.

**Comment by Lusito** [comment]
Thanks for the use case. Sure you can fork and send a pull request. Tho I have a feeling this will not be an easy to isolate task.

**Comment by Lusito** [comment]
Will hit beta soon. Calling it red-list tho, since it basically is an override for whitelists.
I.E. you create a whitelist rule for '*', so all domains are whitelisted, then add a redlist rule for the domains you want to forget after close.
So in short, redlist > whitelist > graylist.

**Comment by Lusito** [comment]
blacklist might come in the form of completely blocking certain domains from setting cookies in the first place.

**Comment by Lusito** [comment]
@tanabi The beta is now available:
https://addons.mozilla.org/en-US/firefox/addon/forget_me_not/versions/beta

Please give it a try and tell me if it suits your use-case.

**Comment by tanabi** [comment]
Hey, cool!  Thanks, I'm taking a look now.

**Comment by tanabi** [comment]
Wow, that works perfect and is exactly what I wanted.  Thank you so much, this is amazing!  I really appreciate it.  You made my day :)
