### ISSUE TITLE
Netflix Not Staying Logged in

### ISSUE THREAD

**Issue by spacemanspiff4455** [Lusito/forget-me-not#121]
I don't know if this is a bug or something I've just completely missed, but I've whitelisted sites that I want to stay logged in to and some of them don't stay logged in. For example, YouTube leaves me logged in without any problems, but Netflix wants me to sign in again every time I open a new instance of the browser. I've also noticed cookies in Firefox's Manage Data window from sites that I've definitely never whitelisted.

**Comment by Lusito** [comment]
Since I'm having no issue with amazon and netflix, I'm assuming you might have your rules configured wrong for them. Make sure you use `*.amazon.com` and `*.netflix.com` rather than `*.www.amazon.com` `*.www.netflix.com`
