### ISSUE TITLE
Updated translations for 'fr': French (français, langue française)

### ISSUE THREAD

**Issue by symbolsymbol** [Lusito/forget-me-not#122]
Your translation have been copied to your clipboard. Paste it here:
### Version 1.0.5 (2018/09/02)
- Résolu d'un bug concernant l'apparition d'une notification a chaque démarrage.

### Version 1.0.4 (2018/09/02)
- Evitement d'un bug Firefox, qui ne nettoyait pas l'historique de téléchargement.
- Evitement d'un bug Firefox, évitant le nettoyage correct des conteneurs de cookies
- Les sookies Locaux (provenant des sites WEB stockés sur votre machine) peuvent être nettoyés efficacement.
- Traduction en Français réalisée par des gens sympas.
- Prise en charge du bouton d'application en direct du traducteur Web-extension.
- Meilleur support du menu de dépassement de Firefox

### Version 1.0.3 (2018/08/23)
- Correction d'un bug dans l'analyseur d'expression de règles
- Traduction (Argentina) espagnol réalisée par [Fabián Pérez](https://www.github.com/thepante)
- Traduction Suédois réalisée par Jo3yA
- Traduction Portuguais réalisée par SW1FT
- Traduction Portuguais (Brésil) réalisée par Victor Bambino
- Mis a jour traduction Serbe réalisée par  Michael Wolf

### Version 1.0.2 (2018/06/03)
- Prise en charge de la navigation au clavier et des lecteurs d'écran

### Version 1.0.1 (2018/05/28)
- Correction de la purge des cookies expirés

### Version 1.0.0 (2018/05/27)
- Ajout d'une icône et d'une info-bulle différentes en mode répétition.
- Locaux du haut et du bas sorabe grâce à @milupo.
- Les utilisateurs peuvent désormais modifier le type de règle appliqué si aucune règle correspondante n'a été trouvée.
- Prise en charge de la création de règles spécifiques à un cookie nommé
- Amélioration de la détection des cookies tiers.
- Correction de bugs avec la suppression des cookies de sous-domaine.
- Prise en charge améliorée de la première isolation
- Nouvelle fonctionnalité expérimentale: purge des cookies périmés à chaque nettoyage.
- Correction de quelques problèmes visuels.
- Beaucoup d'améliorations du code pour une meilleure stabilité et de meilleures performances!
- Plus de 100 tests unitaires pour assurer une bonne qualité!
- Meilleure aide et plus de descriptions.
- Ajout de la déclaration de confidentialité.

### Version 0.9.1 (2018/04/06)
- Bug qui ignorait le paramètre "ne pas notifier" concernant les mises à jour

### Version 0.8.8 (2018/01/24)
- Ajout d'un nouveau type de règle noire pour bloquer complètement les cookies.
- L'isolation de première partie n'empêche plus l'extension de supprimer les cookies (commence à fonctionner avec Firefox 59). Un support amélioré sera bientôt disponible dans une version bêta.
- Correction: en quittant un domaine, en y entrant de nouveau et en le laissant à nouveau avant l'expiration du délai de nettoyage initial, les cookies seraient supprimés trop tôt.
- Correction de bug: les notifications pourraient être remplacées trop rapidement pour que l'utilisateur puisse les voir.

### Version 0.8.7 (2017/12/20)
- La solution de contournement pour l'importation de paramètres ne fonctionne pas correctement dans la fenêtre contextuelle Firefox browserAction.
- Prise en charge partielle des onglets de conteneur: les cookies fonctionnent, pas le stockage local (Mozilla doit réparer quelque chose en premier)
- Ajout de la nouvelle règle "Forget" (rouge) pour autoriser le remplacement d'autres règles (lisez le tutoriel pour plus de détails).
- Correction d'un problème avec le nettoyage de démarrage
- Ajout de tests unitaires
- Ajout d'une option pour masquer les badges
- Ajout d'une option pour choisir l'onglet initialement sélectionné
- Ajout d'une option pour afficher les notifications de suppression de cookies
- Correction d'un problème sur l'exportation

### Version 0.8.6 (2017/12/06)
- Changements de traduction, en utilisant [web-ext-translator] (https://www.npmjs.com/package/web-ext-translator)
- Introduction d'un fichier readme, tutoriel et changelog en extension.
   - Vous pouvez y accéder via le bouton d'interrogation.
- Affichage d'une notification lorsque l'extension a été mise à jour (peut être désactivée).
- Les domaines sans domaine de premier niveau (tels que localhost, intranet, etc.) peuvent désormais être ajoutés à la liste blanche avec une case à cocher.
- Fonction expérimentale pour bloquer les cookies tiers

### Version 0.8.5 (2017/11/25)
- Typo corrigé
- Basculement du type de règle plus lisse
- Bouton permettant d’ajouter de nouvelles règles (avant de pouvoir ajouter une nouvelle règle en appuyant sur Entrée)
- Bouton pour obtenir des informations sur les expressions valides

### Version 0.8.4 (2017/11/25)
- Meilleure compatibilité mobile
- Correction des cookies incognito enregistrés et supprimés

### Version 0.8.3 (2017/11/24)
- Désactivé sur les onglets / fenêtres incognito
- Ajout d'un journal pour voir les domaines des dernières modifications apportées aux cookies
- Ajout de boutons pour pré-remplir le champ de saisie du filtre avec les domaines ci-dessus et l'onglet actuel

### Version 0.8.2 (2017/11/19)
- Quelques corrections de bugs, nettoyages

### Version 0.8.0 (2017/11/19)
- Première version

**Comment by Lusito** [comment]
@symbolsymbol Thanks. I've updated the file, but was it intended to only update the changelog?
