### ISSUE TITLE
Early Access Program

### ISSUE THREAD

**Issue by Lusito** [Lusito/forget-me-not#126]
For all of you dying to try the next version, you can now do this.
But please keep the following in mind:

- Bugs might occur, most of my tests have focused on automated code tests (333 at this point), didn't get to do much real browser testing yet.
- It's recommended to try this in [Firefox developer edition](https://www.mozilla.org/en-US/firefox/developer/) with `xpinstall.signatures.required` set to true in about:config or with a separate profile, as settings are not backwards compatible (so reverting to an older version will require you to double check your settings, especially the timeouts).
- This version will not automatically update. You'll need to uninstall it and reinstall the official version from addons.mozilla.org once it is released.

Here you go: http://lusito.info/fmn-2.0.0.xpi

**Comment by Lusito** [comment]
Actually the worst case would be if a bug caused stuff to get deleted in a payment situation or similar. Imagine you trying to buy something for a lot of money and your cookies got erased in the middle. Or you where to upload an important work at your university and it got lost because cookies where dropped.

I could sign the developer builds, though it would require some extra work. Man, I miss the time when mozilla had support for beta channels. Will do this in the future, for now this will have to do.

**Comment by rugk** [comment]
AFAIK you can upload "beta builds" on Mozilla AMO too, so maybe just distribute them, there? (they are marked as unstable and all these things and can really only be installed if the user chooses to do so)

**Comment by Lusito** [comment]
Nope, that did exist at some point (and I used it back then), but at some point they removed the beta channels.

**Comment by Lusito** [comment]
We're live with 2.0.0 now
