### ISSUE TITLE
Put privacy statement on AMO

### ISSUE THREAD

**Issue by rugk** [Lusito/forget-me-not#127]
In addition to put your privacy statement in the Readme, a better (user-facing) way would be to (also) put it as a "privacy policy" on AMO.

Users can then see it in the sidebar here:
![image](https://user-images.githubusercontent.com/11966684/52177737-e83f1680-27c5-11e9-8f8f-af7c8f46a103.png)

**Comment by Lusito** [comment]
I haven't seen any way to add a privacy policy to the sidebar. Do you know a way?

**Comment by rugk** [comment]
Yep, go to the page where you can edit the "author and license", there you can click "This add-on has a privacy policy.":

![image](https://user-images.githubusercontent.com/11966684/52536052-138dac80-2d56-11e9-872e-4d21420b1b97.png)

**Comment by Lusito** [comment]
Thanks. Done
