### ISSUE TITLE
Consistent wording of rule state

### ISSUE THREAD

**Issue by rugk** [Lusito/forget-me-not#129]
You sometimes refer to the white/grey/black/… rules as white/black/… and sometimes (as in the badge) as N/S/L/I (never/on _s_tartup/on _l_eave/…). (The last ones are actually also translated.)

This is confusing.

To understand the colors used (red/grey/…) is already hard enough for new users (hint: me). When you then also use different terms (and colors?) in the badge, it get's really confusing.

So better stay consistent…

**Comment by Lusito** [comment]
"never", "on startup", etc. are new ways to describe the rules so they are easier to understand.
These new names are only for the upcoming version and should not be in the stable release.

In the upcoming version, there should no longer be old (color coded) names for these rules, as can be seen in the development branch of the translations:
https://lusito.github.io/web-ext-translator/?gh=https://github.com/lusito/forget-me-not/tree/develop

Or have I missed something?

**Comment by rugk** [comment]
Okay, great! Just the "old" (stable) version already used these strings in the badges.

**Comment by Lusito** [comment]
That shouldn't be the case.. back then I hadn't started with the new labels yet.
