### ISSUE TITLE
Error logged to console when new window is opened

### ISSUE THREAD

**Issue by rugk** [Lusito/forget-me-not#130]
During testing my add-on (https://github.com/rugk/mastodon-simplified-federation/issues/14) I noticed your add-on always seems to log some kind of error, when a new popup (window) or tab is opened:

![grafik](https://user-images.githubusercontent.com/11966684/52377382-fd85a080-2a64-11e9-92d7-41da42726b5d.png)

> 22:44:22.991 Error: Could not establish connection. Receiving end does not exist.
background.js:1:17097

I guess, this is not good… :smile: 

I traced it back to your add-on via the URL (and extension ID) shown when you hover over the JS file at the right.

Firefox 65
Linux

**Comment by Lusito** [comment]
Thanks for the report, but this is nothing to be worried about. When using browser.runtime.sendMessage, it will show an error, if noone received it.

I use this to send "hey, settings updated" or similar to tabs (in this case the extension popup). If the extension popup is not there, it will show an error. I'll make sure the error won't show in the future.

**Comment by rugk** [comment]
Yeah, it is just annoying for debugging or so. :smile:
