### ISSUE TITLE
Private Browsing - Why Icon Greyed out 

### ISSUE THREAD

**Issue by Joel889** [Lusito/forget-me-not#138]
Why is the extension's flower greyed out if browsing privately?
My first thought was that the extension was disabled in private windows, but that's not the case. For example, domains with "instant" drop cookies rules will still do so; private browsing or not.

**Comment by Lusito** [comment]
I meant for it to be disabled in private windows, I guess I missed a spot. Thanks for the report.

**Comment by Joel889** [comment]
Would it be possible to put this in a setting to allow users to enable the extension in private browsing. 
Maybe set the default as disabled in private.

**Comment by Lusito** [comment]
Private window support is defined in #15. Will check out how much work it is to do this.
