### ISSUE TITLE
Cannot save customized matching expression in v2.0

### ISSUE THREAD

**Issue by jacobpierce** [Lusito/forget-me-not#141]
**Issue**: Cannot customize a matching expression and save it.

**Environment**: FMN v2.0; MacOS 10.14.3; Firefox 65.0.1

**Steps to reproduce**:
1.) Visit a domain (e.g. `www.xyz.example.com`)
2.) Create a "cleanup" rule based on a matching expression (e.g. `*.xyz.example.com`)
3.) Edit the matching expression (e.g. remove `.xyz`)
4.) Select a rule by which to save it ("on startup", etc.)
5.) Check the saved rule and the matching expression will have reverted to its initial state (e.g. `.xyz` is back in our example)

![fmn-v2-bug](https://user-images.githubusercontent.com/597902/53202968-b529bf00-35dc-11e9-9a37-df856ce8ffbe.png)

Love this plug-in and the updates in 2.0. Thanks guys!

**Comment by Lusito** [comment]
Thanks for the report. I've identified the issue and it will be fixed in the next version.
