### ISSUE TITLE
Issue 145 Simply want to delete HSID cookie on google.com

### ISSUE THREAD

**Issue by snowbound** [Lusito/forget-me-not#153]
Sigh I so much wanted this to work and yesterday it seemed to work fine. Today however when I logged into my Gmail account then opened the YouTube tab its Dark Them was no more. Autoplay was able re-enabled. I set them back on and off respectively and closed Firefox and restarted it. The same thing happened. 

Here are screenshots of the settings have I misconfigured something?

Firefox indicates Forget Me Not requires Container Tabs which are not installed 
![Annotation 2019-03-15 085454](https://user-images.githubusercontent.com/596147/54437065-d2e0d480-4701-11e9-9462-3ed5fa7ef7df.png)
![Annotation 2019-03-15 085707](https://user-images.githubusercontent.com/596147/54437070-d5432e80-4701-11e9-8422-792603a9a547.png)
![Annotation 2019-03-15 085810](https://user-images.githubusercontent.com/596147/54437078-d7a58880-4701-11e9-999e-d417575f5675.png)

**Comment by Lusito** [comment]
Your settings are telling FMN to forget all cookies from google.com that are not set on accounts.google.com. I can't tell you which ones you need for your scenario to work, but I'm guessing that there are some that fit that description.

Container Tabs are included in Firefox. No need to install anything. FMN only uses them if you use them.

**Comment by snowbound** [comment]
Trying a slight change. Will know in a couple of days on whether there are any side effects.

**Comment by snowbound** [comment]
Seems to be working fine now. Been able to force the Gmail log out on browser close without any issues that I can see. Like you mentioned it was deleting all the cookies for the tabs open in the browser before. Now it is only deleting the one cookie for the hsid on startup.

![ForGetMeNotSettings](https://user-images.githubusercontent.com/596147/54557819-0fbefc80-498a-11e9-8bb2-7ebf3c671777.png)

**Comment by Lusito** [comment]
Glad do hear it's working for you :)
