### ISSUE TITLE
Not deleting cookies on Nightly

### ISSUE THREAD

**Issue by streetwolf** [Lusito/forget-me-not#154]
It appears that cookies are not being deleted.  This might be caused by the screenshot of my Fx Options.
![Annotation 2019-03-23 203810](https://user-images.githubusercontent.com/410799/54873407-0ed40380-4dac-11e9-9416-63ccbfbb06b5.jpg)

**Comment by streetwolf** [comment]
The 'cookies' that aren't being deleted are in local storage which I know your add-on can't handle.  I always forget this.  I am still curious as to what the highlighted section means.

**Comment by Lusito** [comment]
FMN can clean local-storage. If you can clarify, where you see the 'cookies', that are supposed to be removed, maybe I can help.

The highlighted section means, that FMN supports Container Tabs. It's a bit of a weird wording, since Container Tabs are included in Firefox by default, they are just inactive as long as you don't use them.

**Comment by streetwolf** [comment]
The 'cookies' are the ones in /storage/default.  I submitted another issue about this and you stated there is no API to do this and you opened up a bug report to try and get one.

**Comment by Lusito** [comment]
I said that there is currently a bug in Firefox that prevents the cleanup from working in some cases. Mozilla is currently investigating/fixing this. See this bugticket:
https://bugzilla.mozilla.org/show_bug.cgi?id=1529122

Normally you should be able to clean those with the "indexed db" cleanup option. Hopefully this will be fixed soon.

If you have a case, where the storage folder still contains a folder "idb" after cleaning indexed db, please help mozilla by providing some feedback in the above ticket.

**Comment by streetwolf** [comment]
Is bug 1529122 supposed to allow FMN to delete the 'cookies' in /storage/default?  I am on the latest Nightly which has this patch and 'cookies' are not being deleted in this location.  For example, going to www.neowin.net puts cookies in cookies.sqlite as well as in /storage/default/https+++www.neowin.net/.

I have neowin.net setup to delete all cookies upon leaving. While the cookie neowin.net is deleted from cookies.sqlite the one in local storage isn't.

**Comment by Lusito** [comment]
That ticket is supposed to fix a bug. Nightly has only been fixed after your comment, so you would have to try again now. According to the developers, the directories are supposed to remain, except for the "idb" directory inside of it.
