### ISSUE TITLE
Manual cleanup broken/not working?

### ISSUE THREAD

**Issue by vshl** [Lusito/forget-me-not#157]
I noticed today manual cleanup doesn't seem to be working. I checked all options, on hitting confirm, I get pulled back to the first tab and it doesn't seem to be doing a cleanup.

**Comment by Lusito** [comment]
Could you clarify, what doesn't get cleaned and how you detect that it doesn't get cleaned? I don't have that issue.

**Comment by vshl** [comment]
Ignore this issue. There was something wrong with my Firefox. It worked after I restarted the browser.
