### ISSUE TITLE
Question about widlcard and hostname

### ISSUE THREAD

**Issue by ReporterX** [Lusito/forget-me-not#159]
1. If I use `*.example.com`, does it work in all the cases?
A. `example.com`
B. `www.example.com`, `sub.example.com` etc.  
I guess it is but I just want to ask to be certain. 

2. How does it work with different containers? Do the rules apply to all containers automatically?

Thank you.

**Comment by Lusito** [comment]
1. Your assumption is correct.
2. Yes, currently, rules apply to all containers. The only difference is, that domain leave is detected per container. So if you leave all instances of example.com have been left in container A, but there are still some open in container B, then cleanup will happen in container A, but not in container B. Container specific rules are on the todo list, but I didn't have the time yet.

**Comment by ReporterX** [comment]
1. What happens if I press "Clean this domain" in container A? Will it only remove the cookies in container A (in other words, not in container B or default container etc.)?

2. If I press "Clean this domain" in the default container, will it remove cookies in the default container only?

3. What if I want to remove cookies in all containers? How to do?

Thank you.

Thank you.

**Comment by Lusito** [comment]
Clean this domain will run cleanup in all containers. There is currently no way to clean only one specific container with FMN.

**Comment by ReporterX** [comment]
I see. Hopefully there will be such an option in future.

Currently it seems the quickest way to clear cookies of the domain in the specific container is to press Ctrl-Shift-I to open the Developer Tools and switch to the Storage tab to delete cookies.
