### ISSUE TITLE
Apply rules on history removal as well

### ISSUE THREAD

**Issue by Lusito** [Lusito/forget-me-not#16]
It's possible to clear history items based on their URL, so there should be an option to apply rules.
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/history

**Comment by rmenessec** [comment]
Is this waiting on a Mozilla bug? If so, can you reference it, so I can vote for it? If not, can you create a bug?

Thanks!

**Comment by Lusito** [comment]
No, there is no Mozilla bug, since it's currently already possible. It's just not implemented in FMN yet.
It hasn't been in my high priority list, since websites can not access this data.

**Comment by Lusito** [comment]
I think you misunderstand the term history in this context. In the context of web-extensions, the team history is describing the urls you visited and some statistics, like when and how many times you visited them:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/history/HistoryItem

It does not include DOM storage, IndexedDB, cookies or anything else. I know this is confusing, since the Firefox preferences page talks about history in a more broad way when it allows you to clean data on exit.

There is a ticket for cleaning browsing data on a per-domain basis here: https://bugzilla.mozilla.org/show_bug.cgi?id=1340511

**Comment by rmenessec** [comment]
Oh.

Okay, is there an open issue for clearing DOM storage periodically (or on start / exit) along with cookies, in FMN? According to the Mozilla bug, the WebExtensions API now supports removing DOM storage by host name.

**Comment by rmenessec** [comment]
Of course it is. I'm a complete idiot. Sorry.

Follow-up question: will FMN support IndexedDB and/or Service Workers at some point?

**Comment by Lusito** [comment]
No worries.. the Firefox's wording confuses me a lot too.

FMN does support cleaning them all at once.
Once https://bugzilla.mozilla.org/show_bug.cgi?id=1340511 is implemented, I will add support for cleaning them with rules applied.

I just created this bug to make better use of it, if you want to vote for it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1464895
