### ISSUE TITLE
[Bug] Cookie Browser not update automatically after changing rules via interface

### ISSUE THREAD

**Issue by ReporterX** [Lusito/forget-me-not#160]
Cookie Browser does not update automatically after creating/changing rules via its interface. You have to leave the Cookie Browser and go back to see the changes.

Firefox 66.0.2 (64 bit) Portable  
Forget Me Not 2.2.1

**Comment by Lusito** [comment]
Yep, noticed this as well. Thanks for the report.

**Comment by Lusito** [comment]
Fixed in the new version
