### ISSUE TITLE
Slowness when installed

### ISSUE THREAD

**Issue by yoasif** [Lusito/forget-me-not#161]
I have been using this add-on for a while but recently started feeling like my browser has slowed down a lot. 

I went ahead and took a profile of browser activity as I opened a couple of reddit tabs and closed some other browser tabs. 

https://perfht.ml/2Z88vNf

I saw a lot of delays in the WebExtensions process, in particular this add-on. 

I am hoping that there is something useful here that can help you remove some of the delay I am seeing here. 

Attached about:support here that can hopefully give you some information. 

[about-support.txt](https://github.com/Lusito/forget-me-not/files/3076038/about-support.txt)

[forget-me-not-settings-.json.txt](https://github.com/Lusito/forget-me-not/files/3076039/forget-me-not-settings-.json.txt)

**Comment by Lusito** [comment]
Thanks for the report. There was indeed a bug in the code related to CheckDeadFrames -> CheckDomainLeaveSet. It will be fixed in the next version.

Did you notice any other place related to FMN? I could only find this one item in your link. Maybe I'm missing something, since I haven't used that tool before.

**Comment by yoasif** [comment]
I'll retry it after the new version comes out and I'll be happy to reprofile if I see slowness. I just noticed that my browser has been lagging for a while now and I finally got frustrated enough to try to figure out what was going on.

**Comment by Lusito** [comment]
The new version has been released. Please re-open if not solved. Thanks again for the report!
