### ISSUE TITLE
Deletes 3rd party cookies in snooze mode

### ISSUE THREAD

**Issue by bege10** [Lusito/forget-me-not#165]
Hi,
I just need the snooze mode for the first time to not have paypal cookies deleted from www.traystatus.com. But forget-me-not still deletes the paypal cookies. The tooltip on the button says "currently disabled" (translated from German)
Firefox 66.0.5, forget-me-not 2.2.2, Windows 7 Professional 64 bit SP1

**Comment by Lusito** [comment]
Hi @bege10, sorry for about the delay. The snooze mode doesn't disable black rules. Did you maybe add paypal to black rules?

**Comment by bege10** [comment]
Black rules are rules to instantly delete cookies, right? No, I didn't have any rules for paypal. Meanwhile I added grey rules (delete at startup) for paypal and paypal related domains to have paypal work correctly. But to use paypal as third party cookies I had to use a browser without the add-on.

**Comment by Lusito** [comment]
Can't reproduce this issue.. I'm using paypal on a regular basis. Could you send me your config?

**Comment by bege10** [comment]
I didn't have any payments with paypal, so I just tried www.google.de. There also third party cookies google.com are removed in snooze mode.
[forget-me-not-settings.zip](https://github.com/Lusito/forget-me-not/files/3321872/forget-me-not-settings.zip)

**Comment by Lusito** [comment]
Thanks for the settings. This seems to be an issue with the experimental option "deny third party cookies". It is not affected by the snooze mode.

For now, try disabling it and instead enable the "remove third party cookies on creation". This should avoid your issues. I will add a fix in the next version.

**Comment by Lusito** [comment]
I've submitted the new version. It might take some time though for it to be approved, since FMN is in the new "recommended extension" program of Mozilla, which requires a more in-depth code review.

**Comment by bege10** [comment]
Thank you very much. Works great.
