### ISSUE TITLE
deleted cookies popup hides tabs

### ISSUE THREAD

**Issue by bendover22** [Lusito/forget-me-not#166]
Overall, the menu UI is much improved than earlier versions.  Good job.
I've noticed the cookies removal popup is positioned right over Fx desktop tabs.
Yes, you can turn off FMN showing when cookies are removed, but not everyone would want that.

You can click the FMN popup to remove it & access the tab or other addon icons, but I find that a bit awkward.  Maybe if it can't be moved (or can't decide where), the popup's opacity can be adjustable, so not to hit the new tab's close button - hidden by FMN's popup - which I've done?

Since the cookie removal notice is by the FMN icon (not by the tab where cookies were removed), I'm often trying to do something w/ the tab(s) that are behind the FMN popup.  But can't until the FMN popup fades.   

The reason I'm often using or changing to a tab near FMN's popup, is the right end of the tab toolbar is usually where the newest tabs open.  Sometimes it's just coincidence that the tab I want to view next happens to be by the FMN icon.

Also, the popup hides part of other addon icons - on my nav toolbar, that also can't be used until FMN's popup fades away.  

Is it possible to make the removal notification not cover the tab row(s) or the nav bar (or possibly bookmark bar - if visible)?  It's open to discussion what's the next best place to put the cookie removal notice, or if there's a not too difficult way for users to choose a position - within reason.

**Comment by Lusito** [comment]
Hi @bendover22.

Sadly, the possibilities to control the notifications are quite limited. I can't do what you are asking.
This sounds like a generic issue with notifications and could be worth creating a ticket on https://bugzilla.mozilla.org/.

You can disable the notification if it bothers you too much (check the settings).

Hope this helps.

**Comment by bendover22** [comment]
Thanks Lusito.  Are you sure there's no control over where (any) addon's
popups about completed tasks should appear?
I think some users wouldn't want to completely turn off the deleted
cookie notices.
I don't have a lot of addons with popups, but some that show popups
(e.g., something was deleted, blocked) either have options where notices
should appear (like NoScript) & others I've used.

Addon drop down (popup) menus (for nav bar icons) don't block tabs. Why
should / would completed task popups be any different?

Offhand, I don't remember any other addons that blocked / interfered
with tabs.

It could be a bug, but I can't believe the default behavior should be to
block access to tabs.  The newer tabs, very likely to get activity.

**Comment by Lusito** [comment]
These are the options I have:
https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/notifications/NotificationOptions

Maybe I am blind, but I don't see any options to position them. I've checked NoScript and I don't see options to position notifications there either.

The only thing I could do, would be to inject notifications into the webpage, which would be very ugly and error-prone.

As said, I think this is more of a Firefox issue than a FMN issue. I've actually read, that it might be OS specific, like on windows notifications would show near the system tray icons.

**Comment by bendover22** [comment]
I looked at the links provided - some time ago.  I replied, but it didn't show up for some reason.  No, I don't see any option to position them, but I'm not an expert (some days, don't reach newbie status).  I misspoke on NoScript (quantum) having option to position certain notifications.  It did in the legacy version.

Do you know the exact ids/classes of those notification boxes/popups for deleted cookie notification?  I wanted to see if there's a way to move it using CSS.
But so far, I can't capture any rules for that popup or see anything in dev tools.  It doesn't obey the "disable popup auto-hide in dev tools browser toolbox when inspecting chrome elements, nor the same option in addon debugger.

When I have addon debugger for FMN open & close a tab w/ cookies, the popup appears but won't stay open, though "disable popup auto-hide" is enabled.  So it's a different type of popup.

I also can't find anything to help in the dev tools addon debugger.  Probably from inexperience using addon debugger, or position info on the generated "cookies deleted popup" wouldn't be found in files or info in the addon debugger.

I'd need to know a bit more about it before filing a bug with Mozilla.
So far, that's the only popup I've seen that hides most of the addon icons - if on the nav bar.  

It also hides the new tab button, if the button is near the right end of the screen.  I have to wait till it disappears before I can use anything the popup's hiding.  Sometimes it takes several seconds to disappear.  It may depend on how much info is in the popup - how big it gets.

**Comment by Lusito** [comment]
Notifications are not a popup by definition. They are using operating-system specific code, which means you probably won't be able to change anything with CSS.

If you don't see other popups having this issue, it's probably because those other popups aren't notifications.

You don't need to specify technical details to open a bug ticket at bugzilla. Just report the issue you are having and make sure you have the correct wording: Notifications, not popups. You could improve that a bit by adding a screenshot, which illustrates the issue. I'm pretty sure Mozillas employees and volunteers can find the issue with that information.

**Comment by bendover22** [comment]
I found a better than nothing work around for the deleted cookies notification,  covering tabs & icons on the nav bar.  At least for Firefox / Mint 18.1 & any 'nix distros that use dconf to hold many settings.  
But Mozilla or distros? should change the top of screen notification container's location to behave like ones appearing at the screen bottom.  Ones at the bottom don't hide tray icons or any open apps tabs on the panel (aka, taskbar).

In Linux, you'll probably need dconfEditor installed (if not already).  Should be available in the distro's own repository.

In dconfEditor, at: "org.cinnamon.desktop.**notifications**" checking the option "fade-on-mouseover" makes the "deleted cookies" - or any - notification fade immediately on mouseover (in Mint). Then tabs or addon icons hidden by the notification can be clicked w/o waiting for notifications to close.  

DconfEditor gives me the option to turn off notifications (not a good idea - affects many notifications).  I have no idea how many other system or apps' notifications might appear in the same spot as the deleted cookies. 

Can adjust the time notifications display - default was 500ms.  Any less & you won't be able to read important notifications.
