### ISSUE TITLE
Very annoying sound when plug in show notificatios

### ISSUE THREAD

**Issue by Lord-Toffa** [Lusito/forget-me-not#169]
It's a simply preferences option... Show the notifications everytime that somethig is deleted, but pleas add the option that remove the volume of the notifications.

Good work man

**Comment by Lusito** [comment]
Sorry, but this is an operating system setting that I can't change. You can probably change it in your OS sound settings somewhere. Firefox doesn't offer an option to make this silent.

Hope this helps.
