### ISSUE TITLE
Protecting/removing single cookies

### ISSUE THREAD

**Issue by Lusito** [Lusito/forget-me-not#17]
A request from Reddit:

> I'd like to preserve individual cookies. Some sites use one cookie to track the user and another cookie to control presentation, like the number of search results per page. I would like to nuke/block the tracker cookie but keep the presentation cookie. A whitelist, maybe with with regexp, might be a good way to accomplish this.

The behaviour for this needs to be elaborated first:
I guess if a single cookie can be whitelisted, then the domain itself should not be whitelisted by the user (so when the normal removal kicks in, whitelisted cookies are protected).

**Example**
User wants one cookie at domain xy.com to remain, but others to be removed. User will not whitelist xy.com, but instead create a cookie protector for the pair of (cookiename@xy.com).

**Comment by OhSoGood** [comment]
Hi @Lusito 
Any news about this enhancement? That would really be so great.... Thank you!

**Comment by Lusito** [comment]
Hi @OhSoGood 
This is quite high on my priorities, but as mentioned in other topics, I've been busy moving to a new city and just got internet hooked up again, so it might still take some time.

Even worse, mozilla just disabled the extension because they couldn't reproduce the obfuscated code, and I had to submit a new version. I hope this works for them now..

**Comment by OhSoGood** [comment]
Good setup so! May I ask why you obfuscated part of the code if the extension is opensource? That could be seen as weird and even as suspect by some...

**Comment by Lusito** [comment]
I use webpack to compile multiple files together so there are only 5 in the result. Each file only uses those parts of the code it actually needs, to avoid long parsing times. Code compression reduces the overall download size and also reduces parsing time.

The code obfuscation is only a side effect of the code compression. Obfuscated code is really only visible to those extracting the extension zip file. Anyone who is willing to do that can just as easily click on the github link.

**Comment by Lusito** [comment]
Yes, cookie name rules are currently more of an expert setting. There are other voices saying a simpler UI for newcomers might be a good idea, so I'll look into making things more comfortable once the kinks have been worked out and maybe other feature requests have popped up to help define what is going to be the next look & feel of FMN.
