### ISSUE TITLE
Firefox Sync credentials get removed, why?

### ISSUE THREAD

**Issue by rickvanderzwet** [Lusito/forget-me-not#170]
The 'Firefox Sync' feature creates a Password Credential with URL `chrome://FirefoxAccounts (Firefox Accounts credentials)`, which get removed on browser restart.

I configured  ForgetMeNot to 'Cleanup Enable' & 'Never clean domains without a top level domain', how-ever it still gets removed. 

I disabled the plugin, and the entry is not deleted, so I am pretty sure ForgetMeNot is removing it, how-ever the logic tells it should remain right?

**Comment by Lusito** [comment]
Cleaning passwords on a domain-level is not possible due to a limitation in the browser interface. You can either clean all passwords or none. You'll have to disable the password cleaning checkbox to keep passwords.

**Comment by rickvanderzwet** [comment]
Work-around works like a charm, thanks.  I "re-implement" the "password cleaning checkbox" by disabled storing passwords by unticking the box "Ask to save logins and passwords for websites", to ensure no (extra) details are stored at all.  

![image](https://user-images.githubusercontent.com/186766/62456086-fb806e00-b777-11e9-9186-f5ec42b5faa3.png)
