### ISSUE TITLE
Add-on does not display notifications in Firefox Nightly under Windows 10

### ISSUE THREAD

**Issue by acornestean** [Lusito/forget-me-not#174]
Description:
FMN does not display notifications when used on Firefox Nightly under Windows 10. This has been tested with the latest version of Nightly -  70.0a1 Build ID 20190819215716.

Steps to reporduce:
1. Launch Nightly
2. Install the latest version of FMN from AMO
Note: As the “Show a notification when the extension has been updated.” option is selected by default, upon installation, on macOS High Sierra 10.13.6, Ubuntu16.04.6 LTS (on all Firefox versions – Nightly, Beta and Release) and Windows 10 Pro 64-bit (only on the Release and Beta versions of Firefox) a notification stating that the add-on has been updated is displayed. On the Windows version of Firefox Nightly, however, this notification is not displayed.
3.  Access a website which asks you to allow cookies (ex. https://www.techradar.com/) and accept the cookies
4. Set up FMN to display notification when cookies are removed, set the delay for domain leave to 5 seconds (in order to see quick results) and set the rule for the website to ‘On Leave’. Also make sure the ‘On Leave’ cleanup option is enabled and the corresponding sub-options are selected
5. Close the tab with the website from Step 3
6. Notice that no notifications are displayed regarding the removed cookies  

Expected result:
FMN should display notifications on Firefox Nightly versions running on Windows 10.
 
Actual result:
FMN does not display notifications on Firefox Nightly versions running on Windows 10.

Note:
The issue occurs only on Firefox Nightly under Windows 10.

![FMN no notification in Nightly Windows 10](https://user-images.githubusercontent.com/50236075/63333700-877ec200-c342-11e9-97bd-15e771231365.gif)

**Comment by Lusito** [comment]
Thanks for the detailed report, but I don't think that is an issue of FMN. This probably has to do with Firefox notifications in general. Take a look at this bugticket, which is probably the same as your issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1498912#c4

Can't reproduce this as I don't have windows 10, but if you think the linked issue is not the same as yours, I can try and see if I can get a virtualbox image with Win10.

**Comment by acornestean** [comment]
Hello,

I have further investigated the issue myself and observed that other add-ons will not display their notifications either, when installed in Nightly on several versions of Windows. So this is clearly not an issue with FMN, but with Firefox. Sorry for any inconveniences and thank you for the quick feedback.

**Comment by Lusito** [comment]
No worries. Hope this gets resolved soon.
