### ISSUE TITLE
Outlook.com data

### ISSUE THREAD

**Issue by Kevinokokokok** [Lusito/forget-me-not#175]
I can't get Forget Me Not to clear data (on "Leave") after leaving Outlook email site.  When I look at Firefox's "Manage Data" section after leaving the webmail site, Outlook.Live.com is still there with 64kb of something (which is created when you log in).  The ForgetMeNot panel does list it and it's set at LEAVE.  I changed the domain leave cleanup delay to 1 second, to no avail.  I do not have an FF exception set.

**Comment by Lusito** [comment]
This is just some meta-data Firefox stores internally. I known it's confusing as hell to see remaining data.

Just to show you, this is happening without the webpage doing anything, here is a demo-page I just created:
http://lusito.info/storage/

It will show and store cookies, local storage and indexeddb.
On the first visit, you'll see:

> Cookie:I don't remember you
> Local Storage:I don't remember you
> IndexedDB:I don't remember you

When you refresh the page, it'll show "I remember you" on all items.
Now clear all data using FMN manual cleanup. You'll see it reverting to "I don't remember you".
Close the tab and do a manual cleanup again. Now open Firefox options, go to manage data and search for lusito.info. You'll see 64KB left behind. This datta is nothing I store in this demo-page. It's just something Firefox remembers and I no extension can clear at this time.

I hope this gives you some comfort.

I'm working with Mozilla to improve the situations, but the sad truth is, that many of my issues on Bugzilla stay open for years before they get implemented in Firefox. Looking at how this is purely cosmetical (there is no data left behind the webpage can access), I try to push only the non-cosmetical tickets that add value to extensions.

**Comment by Kevinokokokok** [comment]
Thanks very much for this explanation and example.  I was keeping the add-on anyway, because even with what I thought to be left behind tracking data, FMN seemed to be cleaning up better than the other cleaners I've tried.  Your response adds significantly to my peace of mind!  (And considering the backlog, it's certainly prudent to focus your energies on pushing improvements that are more than cosmetic.)  I appreciate your time and efforts.  The value you and developers like you (most especially those who further contribute by responding to user concerns) add to the FF browser is inestimable.
________________________________

**Comment by Lusito** [comment]
Thanks for the kind words.
