### ISSUE TITLE
add delay option for "Instantly"

### ISSUE THREAD

**Issue by rubaboo** [Lusito/forget-me-not#185]
Could you add an option of allowing the cookie to be written but then deleted after some delay. Because "Instantly" prevents some things on a page from starting.

**Comment by Lusito** [comment]
In theory that would be possible, but I don't think it's a good idea, as the time really varies depending on how long it takes for the website to get to the point where it doesn't need them anymore. What's wrong with using the "on leave" option?

**Comment by rubaboo** [comment]
To clarify, I was thinking of adding an option "Delay for instant cleanup in seconds:", but I agree, this option would only make sense in a cleanup rule, not in global settings. So, if you can add this to the "Create rule" dialog, that would be great.

**Comment by rubaboo** [comment]
A particular use case is as follows (it's a bit of a "cheat", if you don't mind). There is a media player that limits the number of times I can "preview" a track. If I set to clean cookies on leave, then I have to close the tabs for the domain and reopen the ones I want again. But if I clean instantly, the player does not start at all. So I need to let it save the cookie, but delete it once the player has started (so I'm guessing a delay of less than a second would be enough).

**Comment by Lusito** [comment]
Adding a delay per rule is not easily added, so I'm hesitant to do this.
Have you tried using the "Clean this Domain" button on the first tab of the popup? It's just two clicks.
