### ISSUE TITLE
Updated translations for 'fr': French (français, langue française)

### ISSUE THREAD

**Issue by Billyboy1** [Lusito/forget-me-not#190]
Your translation have been copied to your clipboard. Paste it here:
Change setting_downloads (Downloads) from "Téléchargements" to "Historique des Téléchrgements"

**Comment by Lusito** [comment]
Thanks @Billyboy1, I have just updated it (will arrive with the next version).

Could you please have a look at the tutorial section? It seems that the parts "History" and "Downloads" have been merged into one item, even though they are separate items.
