### ISSUE TITLE
Automatic delete does not work

### ISSUE THREAD

**Issue by jzilg** [Lusito/forget-me-not#191]
The extension only deletes cookies after clicking the "Clean this Domain" Button in the extension menu.
No matter what rule I choose for a domain. The cookies are neither deleted after the set delay for leaving the domain or after restarting Firefox.

Forget Me Not 2.2.5
Firefox 69.0.3
MacOS 10.15

**Comment by Lusito** [comment]
I'm guessing you have not enabled the respective cleanups in the settings. The cleanups are disabled by default, to avoid accidental removal of data while you haven't set up your rules yet.

I guess this could be made more obvious. I've created #192 for this.

**Comment by jzilg** [comment]
Ah ok. Now it works. Thank you for the help! Maybe at a shot startup tutorial on the infopage of the Addon?
