### ISSUE TITLE
Confusing Addon - How to Use?

### ISSUE THREAD

**Issue by koolx** [Lusito/forget-me-not#214]
I'm confused as to how to work this addon. I only want to keep the cookies I want to keep and to delete unwanted cookies and local storage data. How do I do that?

**Comment by Lusito** [comment]
There is a tutorial included in the add-on. When you click on the toolbar icon, there is a blue questionmark circle in the top of the popup. Click it to get to the tutorial. Once you have read it and have more specific questions, I will be happy to assist you.
