### ISSUE TITLE
Delete a rule?

### ISSUE THREAD

**Issue by eadamy** [Lusito/forget-me-not#219]
Early on, I setup a rule for *.google.com to Never delete. I see that Google is adding cookies I don't want so I want to remove this domain rule and set rules by subdomain. I can find no way to remove the domain level rule. If I set it to Leave, it clears all of the Google cookies and if I set it to Never, it leaves cookies I don't want. 

I found the forget-me-not@lusito.info.xpi file which I assume includes the rules; however it is encrypted.

**Comment by Lusito** [comment]
Sorry about the delay. You can remove rules by clicking on the "X" button at the right side of the rule. The xpi file does not contain the rules. It contains the add-on.
