### ISSUE TITLE
Some settings on twitter.com reset despite exception rule

### ISSUE THREAD

**Issue by monzta** [Lusito/forget-me-not#225]
- Windows 10
- Firefox 74 (latest beta)
- Forget Me Not 2.2.6

I added `*.twitter.com` as an exception but still when I restart Firefox and go to twitter.com, some settings like [font size and theme](https://twitter.com/i/display) and "Latest tweets" flag are not saved.

**Comment by Lusito** [comment]
Thanks for the report. I don't use twitter, so it's hard to tell from here. I'd have to know how these settings are being stored.

If they are stored in something that cannot be cleared on a per-domain basis, like IndexedDB, then a restart will clear those settings.

You could try to disable all cleanup checkboxes and then start enabling them one by one to find out which cleanup rule actually deletes your data. You can do this via manual cleanup. Just make sure to either close all twitter tabs or check the checkbox "Protect currently open domains if "Apply Rules" is checked"

**Comment by monzta** [comment]
@Lusito Thanks! I can confirm it's indeed IndexedDB. If cleared, the mentioned Twitter settings are lost.
