### ISSUE TITLE
Question on custom rules

### ISSUE THREAD

**Issue by pcause** [Lusito/forget-me-not#230]
I want a custom rule to apply just to a site.  I go to foo.com.  I set foo.com to be never.  I a;lso want to make "foo.net" never but only on the site foo.com.  Does the cutomer rule only apply to the site I am on when I opne the UI to create rules?

**Comment by Lusito** [comment]
Hello and thanks for the report.

This kind of rule is currently not possible. What comes closest is to deny third-party cookies, but that is an all-or-nothing choice right now.

Can you explain your use-case a bit more, so I can see what solution might fit best?

**Comment by pcause** [comment]
thanks.  I can find a work around
