### ISSUE TITLE
Clean All Data Except Protected Cookies at One Time

### ISSUE THREAD

**Issue by MDJonas** [Lusito/forget-me-not#233]
I'm very new to this...sorry. Can FMN clean all browsing data, at one time, except for cookies with the rule NEVER?  If so, how do I this.

**Comment by Lusito** [comment]
Hello @MDJonas,
yes you can by following these steps:
- Open the popup
- Click on the trashcan (Run manual cleanup)
- Select the options like this:

**Careful though**, this erases everything, even history! Adjust accordingly if you want it differently.

![instructions](https://user-images.githubusercontent.com/1135267/80411351-5a6cb100-88cc-11ea-92a8-cb68de007eb0.png)

**Comment by MDJonas** [comment]
I wanted to make sure that this option deletes ALL the cookies that are not protected by me.

Michael



“Dogs sit with you at work;
Cats sit on your work.”
		          Pam Brown

**Comment by Lusito** [comment]
Deleting all cookies and all browsingdata are two different things. Browsingdata includes cookies, history, localstory, etc.

If you only want to delete cookies, you must uncheck all other options.

The shield icon on the right shows you that it will protect what you set to NEVER. if a red line is drawn over it, it will your rules will be ignored. You can toggle this icon via click.

**Comment by MDJonas** [comment]
I apologize for not being clearer.  I’ve set up “Never” rules for a number of website.  I want to be able to delete History, etc. (I see know how to choose) and all the cookies that are not included in my “Never” rules.

Thank you for being patient.

Michael



“Dogs sit with you at work;
Cats sit on your work.”
		          Pam Brown

**Comment by Lusito** [comment]
As I said, the shield protects the data which matches your NEVER rules.
If there is no shield (or the shield has a red line over it), that means all data will be removed.

I hope this clears it up. If you are still unclear, try to give me a use-case scenario and I will try to explain it based on that.

If that answers your question, feel free to close this issue.

**Comment by MDJonas** [comment]
Again, thank you. I think I understand.

I’m going to post a very favorable review, is there somewhere I also submit a payment to you?

Michael



“Dogs sit with you at work;
Cats sit on your work.”
		          Pam Brown

**Comment by Lusito** [comment]
Happy to help.

Right now I have no plans to accept monetary donations (I don't like the extra work introduced by having to declare this with the government).

The only kind of donations I accept are:
- Reviews
- Translations to a new language (or improvements on existing ones)
- Help with writing new features or bugfixes.

**Comment by MDJonas** [comment]
I had posted a review (5 stars) under the name Michael-Desert-Rat…and I meant it.

Thanx for developing a great extension.

Michael



“Dogs sit with you at work;
Cats sit on your work.”
		          Pam Brown

**Comment by Lusito** [comment]
Thank you very much.

If you actually want to spend some money to help this extension, consider donating to the Mozilla Foundation: https://donate.mozilla.org/

Looking at how everything nowadays turns into Chrome, I think it's important to keep the remaining alternatives alive.

**Comment by MDJonas** [comment]
I removed everything  Google from my Mac, and wife’s Mac, some time ago…so making a Mozilla donation is fine with me, I’ve done it before.

Michael



“Dogs sit with you at work;
Cats sit on your work.”
		          Pam Brown
