### ISSUE TITLE
Clean history 

### ISSUE THREAD

**Issue by kien5436** [Lusito/forget-me-not#240]
I use `On startup` option to clean some domain after browser restart but it doesn't work properly. The extension only removes cookies but not histories. Therefore, I ran manual cleanup and nothing happen. Would you consider this bug?

**Comment by Lusito** [comment]
Hi @shhlkien,

FMN has a lot of options. I'm guessing, that your options prevent the history from being deleted on startup.
Make sure you enabled the checkbox for "History" in the "On Startup" row as well and if you have the "Apply Rules" checkbox on, also make sure, that your rules do not protect those domains.

**Comment by kien5436** [comment]
![image](https://user-images.githubusercontent.com/23404165/85810060-0a06b800-b784-11ea-9e5a-54f076c68f65.png)
![image](https://user-images.githubusercontent.com/23404165/85810104-2e629480-b784-11ea-8c0d-f36bc491c623.png)

I use settings as above, when I click manual cleanup, nothing happen!
Then I uncheck "Apply Rules" for history, it clear all my histories though I check "Protect domain". Also I do the same with cleanable table, it does not work.\

![image](https://user-images.githubusercontent.com/23404165/85810238-9c0ec080-b784-11ea-96ce-398afcc45f64.png)

Can you explain how the rules are applied?

**Comment by Lusito** [comment]
Is the domain maybe still open? Try unchecking the "Protect currently open domains" when running the manual cleanup.

**Comment by kien5436** [comment]
I use `On startup` rule so the domain is not open. Uncheck protect domain cause the extension to delete all history.

**Comment by Lusito** [comment]
I meant unchecking the "Protect currently open domains" but still enable the Shield ("Apply Rules").

If you have "Apply Rules" enabled, then your rules should be respected. Maybe your rules don't have a wildcard (`*`)?

If you export your settings (settings->general tab) and send them to me, I can try reproducing this.

**Comment by kien5436** [comment]
Sorry for the late answer, I don't have my computer in several days. Here my settings, hope you can help

[forget-me-not-settings.zip](https://github.com/Lusito/forget-me-not/files/4852636/forget-me-not-settings.zip)

**Comment by kien5436** [comment]
@Lusito I've found something was wrong with this extension. I tested with the default config when installing. Domains have format `domain.*` can't be deleted, such as `github.com`, `codeigniter.com`, etc. Otherwise, some other domains with `*.domain.*` are so. Cookies and local storage is working well but not history.

**Comment by Lusito** [comment]
Sorry for the huge delay. I didn't get to anything these past months.

I tried reproducing this with your config and history entries for codeigniter.com get removed correctly on startup. Not github.com, since you've whitelisted it.

Do you maybe have other extensions, which might interfere?

**Comment by kien5436** [comment]
I tested with only your addon enabled and it worked. :D 
Thank you.

**Comment by Lusito** [comment]
Glad to hear. If you ever find out what other add-on caused the issue, please let me know.
