### ISSUE TITLE
Cookies Cleaned Notice

### ISSUE THREAD

**Issue by MDJonas** [Lusito/forget-me-not#252]
I'm using Firefox 80.0.1 (Mac).  Until recently,  when I ran manual cleanup, and then exited FF, when I reopened Firefox I'd gotten a notice (upper right) showing the numbers of cookies cleaned.  That notice no longer comes up.  Is that because of changes in the new update of Fireofx?  Can it be corrected?

**Comment by Lusito** [comment]
I'm on 80.0.1 too (Windows) and still get notifications. Check if you have the option enabled in the settings->general tab of FMN.

Keep in mind though, that when you run manual cleanup the notifications should appear instantly and not after restart.

Notifications on restart of Firefox should only appear if a cookies have been removed during startup of firefox. If that happens depends on your settings and rules.

Edit: I've just tried if notifications happen on startup cleanup and they do show up for me.
Maybe something changed in Firefox for mac. Do you get any Firefox notifications?

**Comment by MDJonas** [comment]
Perfect!!! Thank you very much.  The Cookie-removal notification came up right after I ran the manual cleaning.

Michael


"If your parents didn’t have children, 
chances are you won’t either.” Dick Cavett
