### ISSUE TITLE
Android: Tapping back (UI or navigation toolbar) after going to trash (perform manual cleanup) does nothing

### ISSUE THREAD

**Issue by yoasif** [Lusito/forget-me-not#256]
Steps to reproduce:

1. Go to add-on settings from menu
2. Tap trash icon
3. Press back on Android navigation toolbar *or* use back button in Fenix UI 

What happens:

Nothing. User must tap "Cancel" to get out of this UI.

Expected result:

Tapping back takes me back to the main UI (like cancel).

**Comment by Lusito** [comment]
I'm gonna close this as a duplicate of #257
