### ISSUE TITLE
Forget Me...Stopped Work, Won't Open

### ISSUE THREAD

**Issue by MDJonas** [Lusito/forget-me-not#259]
I'm using Firefox 81.0.2 with the current version of Forget Me...the extension simply stopped working, and the Tool Bar icon does not open; it just shows a white line where the drop down should be. (Screenshot).
![Screen Shot 2020-10-13 at 1 06 04 PM](https://user-images.githubusercontent.com/34040641/95910402-df516700-0d54-11eb-808b-e9b64daf85ea.jpg)

**Comment by Lusito** [comment]
Thanks for the reports. I can't reproduce this. Can you try the following?
- Open about:debugging in a new tab.
- Click on "This Firefox" in the left sidebar
- Look for Forget Me Not and click on the "inspect" button
- Open the FMN popup
- Check for errors in the console.

Another thing you could try:
- Open about:debugging in a new tab.
- Click on "This Firefox" in the left sidebar
- Look for Forget Me Not and click on the "manifest URL" link
- replace `manifest.json` in the URL with `views/popup.html`
- Does it show correctly?
- Open the developer console (press F12) and switch to the "console" tab
- Check for errors

Some of the errors you'll see are expected. For example, you can ignore:
- sendRemoveListener on closed conduit.
- Could not establish connection. Receiving end does not exist.
- downloadable font: kern

Anything you changed lately except for a firefox upgrade?

**Comment by MDJonas** [comment]
Thank you for the information.

What I’d already done is completely remove FMN and then re-install it, and it’s working perfectly.

I’ll keep your instructions and use them if the problem comes back.

It’s a GREAT extension….

Michael


"If your parents didn’t have children, 
chances are you won’t either.” Dick Cavett

**Comment by Lusito** [comment]
Sounds like your extension data might have been corrupted. I've heard of this happening rarely when firefox crashed during saving the settings.

**Comment by MDJonas** [comment]
FMN is working perfectly now…as I said before, it’s a great extension.

I’m going to leave a very positive review; do you also have a place for me to make a donation?

Michael


"If your parents didn’t have children, 
chances are you won’t either.” Dick Cavett
