### ISSUE TITLE
No Access to Preferences

### ISSUE THREAD

**Issue by altjira** [Lusito/forget-me-not#26]
How does one access the preferences? The features sound great, the screenshots look great, but there is no Preferences button on the Add-ons Manager like my other add-ons, no listing in Edit>Preferences, no menu item under Tools. I've disabled the Pop-Up Blocker, even though I have no settings to import. The instructions tell me to check the settings, but don't tell me how.

Running Firefox 57.0.1 64-bit on Fedora 26. Adding screenshot of Add-Ons Manager to show other, possibly conflicting add-ons.

![screenshot_2018-01-06_07-18-29](https://user-images.githubusercontent.com/5146912/34639659-3571e81e-f2b2-11e7-8137-7703b46ec675.png)

**Comment by Lusito** [comment]
The preferences are all accessible from the popup (click on the blue flower in your toolbar on the right side).
I'm currently on vacation, but once I'm back, I will check if it's possible to show the dialog from the preferences button, so this won' confuse newcomers.

**Comment by Lusito** [comment]
The popup blocker fix is not required anymore. I guess I forgot to remove that notice.

**Comment by altjira** [comment]
I see now. I couldn't figure that one out. I would suggest you modify your description to something like:

> Newcomers:
> Some settings are disabled by default to avoid accidental deletion. **Access the settings by clicking the toolbar icon and** Check the**m** <s>settings</s> to activate them.

**Comment by Lusito** [comment]
I have adjusted the description. Thanks for reporting.
