### ISSUE TITLE
A little help please

### ISSUE THREAD

**Issue by rebop** [Lusito/forget-me-not#290]
I am having to rebuild my browser from scratch. I would love to copy all my previous settings from Forget Me Not to the new browser. Is there a way to export / import? Can you tell me what file holds all this info so I can copy and replace the new file? 

Would REALLY appreciate the help.

Thanks.

**Comment by jasperweiss** [comment]
It's right here:

![image](https://user-images.githubusercontent.com/29832921/127172493-4aab4808-f525-4673-977d-eb344395ec9f.png)

**Comment by rebop** [comment]
Thanks. Appreciated!
