### ISSUE TITLE
Is "clean plugin data" limited to plugins

### ISSUE THREAD

**Issue by Joel889** [Lusito/forget-me-not#39]
Is "clean plugin data" limited to plugins or does it also clean extension data?

**Comment by Lusito** [comment]
As far as I understand it, extensions are handled differently, but honestly, I haven't found anything that specifies what exactly gets cleared by it.
Since my web-extensions settings are kept, at least local-storage of the plugins are left untouched.

**Comment by Joel889** [comment]
I noticed the search box is being cleaned during manual cleaning. Perhaps that's part of it?

**Comment by Lusito** [comment]
What search box? Do you have a bug or is this still just a question of how it works?

**Comment by Joel889** [comment]
I meant to post this here:
https://github.com/Lusito/forget-me-not/issues/36

We were trying to figure out what various on-demand cleaning settings do. I noticed that the FF search box is cleared when doing on demand cleaning and was wondering if it is one of the mysterious settings.

**Comment by Lusito** [comment]
"clean plugin data" does not clear the search box.. "clean form data", however does.
