### ISSUE TITLE
Mouse-over descriptions

### ISSUE THREAD

**Issue by Aggrobatics** [Lusito/forget-me-not#43]
When setting a new rule, the colors are not explained. White, grey, red and black are only explained in the general app-description. A mouse-over popup on the dropdown menu would be very helpful.

**Comment by Aggrobatics** [comment]
Another thing I noticed: upon adding a new rule, the 'rule'-tab only displays the recently added rule. It does not switch back to the list of existing rules, until the app's frame is closed and opened again

**Comment by Joel889** [comment]
I know you provided a help file, but perhaps brief tooltips could be added to almost all settings?
