### ISSUE TITLE
Displayed tab after setting a rule

### ISSUE THREAD

**Issue by Aggrobatics** [Lusito/forget-me-not#45]
Adding a new rule, does not bring you back to the recently selected tab (e.g. log). In fact, it does not even show the current rules, but stays on the newly set rule, until the add's frame is closed and opened again. A skip back to the last tab (in app frame) or displaying all currently set rules would be handy

**Comment by Joel889** [comment]
I just added a few rules, and it's somewhat confusing not being able to see all active rules. I wasn't sure what happened to all the other rules and where to find them. I think this is a user interface issue that could be made even better.
