### ISSUE TITLE
Ambiguous color for "white"-rule-selection

### ISSUE THREAD

**Issue by Aggrobatics** [Lusito/forget-me-not#46]
The rule-type 'white' has an ambiguous color scheme. In the dropdown menu it is displayed as deep blue, but when selected (not marked), it turns white. Straight white would seem slightly more intuitive and avoid confusion with the bright-blue color of the marker.

**Comment by Lusito** [comment]
It seems I have a bug on my linux firefox preventing me from seeing the dropdown correctly, but I'm assuming, that the deep blue you are talking about is the selection color. That might indeed be a bit confusing, but avoiding this would require creating a custom dropdown menu which does not rely on the select/option tags.

I have to fix the linux dropdown anyway, I'll see if I can do anything about it.

**Comment by Lusito** [comment]
Going to close this, since there is no way to nicely solve this. Badges only support white text color and you can't set white text on white background. People will have to live with blue = white rule for now.
