### ISSUE TITLE
Global Blacklist as default with ability to allow overrides?

### ISSUE THREAD

**Issue by Radagast** [Lusito/forget-me-not#50]
I know there's a blacklist option already and perhaps I misunderstand how it works, so forgive me if I'm just being dumb!

Basically, I'd like the option to simply block all cookies as the default option. Once done, I'd like to be able to selectively allow sites to set cookies, either for a session or permanently. 

This is basically how I used to do things, with an addon, prior to webextensions and how I still do, it's just that the native firefox UI for managing this is pretty horrible. 

Is this possible?

**Comment by Lusito** [comment]
This is currently not possible. I guess it's a perfectly valid situation, that I didn't think of.
Perhaps create a setting that defines the default behavior to use if no matching rule was found.

**Comment by Radagast** [comment]
If I understand correctly, that sounds like it could work. Basically, if no other rule exists, block?

**Comment by Lusito** [comment]
Yes, but the user would be able to say if the default should be red/white/gray/black.
