### ISSUE TITLE
Bigger spacing between Local Storage and Apply Rules label

### ISSUE THREAD

**Issue by milupo** [Lusito/forget-me-not#51]
Hi Lusito,

please set a bigger spacing between the text "Local Storage" and the checkbox for "Apply Rules" to the right of it on the Settings tab. The Sorbian translation "Lokalny składowak" is too long to fit in the gap so the word "składowak" is moved to the next line. The checkboxes "Apply Rules" could line up with those of "Downloads", "Passwords", "Plugin Data", and "Server Bound Certificates" in the area below them.

Thanks,
Michael

**Comment by Lusito** [comment]
Not sure if just increasing the width is the appropriate way to do this.. I'll see if there is a better way to make this work with different translations.

**Comment by Lusito** [comment]
@milupo is this theoretical?
I've just checked and wrapping works fine for me. All lines below the lines which are wrapped end up in a position that is correct.

**Comment by Lusito** [comment]
I'm assuming this is solved by now. If not, please re-open.
