### ISSUE TITLE
Local Storage grayed out on FF59?

### ISSUE THREAD

**Issue by Kieran-X** [Lusito/forget-me-not#58]
Hello,

I've been using the beta version of FF (60), but has been slow recently so switched back to stable (59). Clearing local storage works fine on the beta, but on stable it doesn't work?

https://i.imgur.com/R6l2fU1.png

Thanks

**Comment by Lusito** [comment]
do you by any change have fingerprint protection on? (see #57)

That checkbox gets disabled if Firefox reports a version < 58. Aside from #57, I know of no other effect causing this to be disabled.

**Comment by Kieran-X** [comment]
That did the trick. Thank you very much.

Odd though, privacy.resistFingerprinting was set to True on the beta also but that didn't have any affect.

Ah well. Problem solved. :')
