### ISSUE TITLE
Background color on dark themes can be hard to read

### ISSUE THREAD

**Issue by bberberov** [Lusito/forget-me-not#62]
The default colors on dark themes can be hard to read.  Changing the setting in `General` > `Language and Appearance` > `Colors...` > `Use System Colors` to off can fix it, but a default dark color might be a better solution.  Screenshot: 

![fmn](https://user-images.githubusercontent.com/7432115/40265128-a798c1ec-5b21-11e8-93a1-ae5da21500b7.png)

**Comment by Lusito** [comment]
Thanks for the report. I will make sure this works in the next version. Although I find it weird that this doesn't happen for me. What OS are you using?

**Comment by bberberov** [comment]
`Linux`, `KDE`, `Breeze Dark`, and the `Dark` `Firefox` theme, not `Default`.

I looked briefly at that patch and I think it should fix it.
