### ISSUE TITLE
UI Looks Squashed in Overflowed Menu

### ISSUE THREAD

**Issue by Rictusempra** [Lusito/forget-me-not#70]
![image](https://user-images.githubusercontent.com/16912240/40788016-8e1e385c-64de-11e8-9ade-00bbf550e76e.png)

Another good example:

![image](https://user-images.githubusercontent.com/16912240/40788036-9b00fa5a-64de-11e8-8238-b6e41dea60f4.png)

**Comment by Lusito** [comment]
Not sure why the width of the popup is that small for you.. normally it should be wider.
What browser are you using? You seem to have some weird title bar for extension popups that I've never seen before, which leads me to believe you have something special going on with your browser.

**Comment by Rictusempra** [comment]
@Lusito 60.0.1 x64 on Windows 10 1803

**Comment by Lusito** [comment]
I will investigate where this comes from. Thanks for reporting. Currently, the UI is depending on a minimum width. I would have to redesign the UI completely to make this work with smaller widths.

Not sure why Firefox would force such a small width for popups on windows 10. I have the same Version and on Windows 7 I don't get that kind of behavior. Do you have something else that could make this version behave differently? Like a touchscreen maybe? (just guessing here)

**Comment by Rictusempra** [comment]
@Lusito not sure. But I can tell my screen is not for touch design definitely.

**Comment by Lusito** [comment]
Those who are able to read have a clear advantage.. I skipped the "overflowed menu" part of the title.
I can reproduce this when moving it into the overflow menu. I will try to improve this with #67.

#67 won't happen within the next couple of days tho, so in the meantime, all you can do is move it out of the overflow menu. Sorry about that.

**Comment by Lusito** [comment]
Closing this ticket, as it will be taken care of with #67

**Comment by Lusito** [comment]
Just a sidenote: [This ticket](https://bugzilla.mozilla.org/show_bug.cgi?id=1373490) suggests that it might be  fixed in the future directly by Firefox.

**Comment by Lusito** [comment]
I know, it's been a while, but Version 1.0.3 improves the UI in the overflow menu.
