### ISSUE TITLE
Cookies are not being removed

### ISSUE THREAD

**Issue by OhSoGood** [Lusito/forget-me-not#73]
I let a comment on issue #59 , as I'm facing the same issue on two different computers, the second being brand new and having only a subset of extensions the other has (noscript, ublock origne, decentraleys, smartreferer).
Anything than I can do to explore the problem?

**Comment by Lusito** [comment]
Hi, Sorry.. I've been on a business trip the past week. I will look into it as soon as possible.

**Comment by OhSoGood** [comment]
It seems I "solved" it but in a weird way. In the rules tab, I had the default behavior when no rules set to "Forget". I changed it to Block, closed Firefox and set it back to Forget, and now it works. Not very satisfactory from a developer point of view, but at least it did it. I let you decide if you wish to close the case.
Anyway I'm so glad it works now! Thank you.

**Comment by Lusito** [comment]
Thanks for the information.. I haven't been able to find out the reason why this setting would affect this, but I'll add some reinforced checks to make sure settings don't contain invalid values to make sure this doesn't happen again.

**Comment by Joel889** [comment]
Here is another example of cookies not being removed (Firefox 63.01):
https://craigslist.org

Click on any listing and click the "x" the hide it. Notice how it says on the upper right corner "1 hidden".
Clean all cookies, storage, etc.
Close the browser.
Re-open the browser and go back to the site. The upper right corner still remembers the listing that was hidden.

CCleaner shows the craigslist cookie, and is able to delete it. Once it is deleted using CCleaner, craigslist no longer remembers the listings that were hidden by the user.

What kind of cookie is this?

**Comment by Lusito** [comment]
I can't currently check this, but I'm gonna make a good guess here, and say that it's probably a HSTS "supercookie", see also https://github.com/Lusito/forget-me-not/issues/27#issuecomment-394838472

**Comment by Joel889** [comment]
No, that's not it. I know that CCleaner is showing HSTS cookies and will remove them, and deleting SiteSecurityServiceState.txt will get rid of a good chunk in CCleaner's list.

Anyway, I emptied SiteSecurityServiceState.txt, restarted the browser (file is still empty), but CCleaner is still showing the craigslist cookie and craigslist is also still remembering the hidden listings from before.

**Comment by Joel889** [comment]
The "cookie" is stored in 
http://kb.mozillazine.org/Webappsstore.sqlite

> webappsstore.sqlite contains DOM Storage data. This data is set by web sites much in the same way as cookies. 

Not sure if this can be cleaned by an extension. But the fact that Mozilla won't display it nor clean it when instructed is disappointing.

**Comment by Lusito** [comment]
dom storage = local storage. At least that's what it's supposed to be. Thus it should be removed if you configured FMN to remove local storage.

Can't really reproduce this issue on craigslist.

**Comment by Joel889** [comment]
I guess something must be wrong on my end.
Just to make sure, when you go to this site and make changes:
https://mdn.github.io/dom-examples/web-storage/index.html

After cleaning everything and revisiting the website, none of the custom settings stick?

**Comment by Joel889** [comment]
Try the following:
1) Go to: https://mdn.github.io/dom-examples/web-storage/index.html
2) Change the picture to the crocodile.
3) Clean storage using your addon.
4) Reusing the same tab, go to https://mdn.github.io/dom-examples/web-storage/index.html
5) The picture should revert back to Firefox (indicating that storage was cleaned successfully).
6) repeat steps 2, 3, 4.
7) The picture is still the crocodile.

**Comment by Joel889** [comment]
Try the following:
1) Go to: https://mdn.github.io/dom-examples/web-storage/index.html
2) Change the picture to the crocodile.
3) Clean storage using your addon.
4) Reusing the same tab, go to https://mdn.github.io/dom-examples/web-storage/index.html
5) The picture reverted back to Firefox (indicating that storage was cleaned successfully).
6) repeat steps 2, 3, 4.
7) The picture is still the crocodile.

The only way to clean storage for that site the second time, is to close the tab, open the **same** page again in a new tab, and then cleaning it.

I don't protect currently open domains when cleaning on demand. That's how I must have ended up with all this junk inside webappsstore.sqlite. I would clean on demand with several tabs open. I keep surfing inside those tabs, which means the entries that were just cleaned get re-created inside of webappsstore.sqlite. Eventually I'll close the tabs, but might never revisit the website, hence webappsstore.sqlite for those webpages will never get deleted.

**Comment by Joel889** [comment]
Do you know when the next version will come out?

**Comment by Lusito** [comment]
Since the current Version still needs some work and has a lot of rewritten code, that might not be perfect yet, I'm not gonna publish a new version before Christmas, as nobody wants lost cookies or similar during the holiday time.

I'm hoping for early January, but it depends on how much time I am able to spend. Sorry this version takes so long, but it really is quite a big rewrite of existing code.

**Comment by OhSoGood** [comment]
@Lusito  : thank you so much for your time and your consciousness on forget-me-not. Keep up the track and bring us a nice new Year baby!
Merry Chirstmas (of course)
