### ISSUE TITLE
Invalid rule matching. (Matching end of string and escaping special characters especially the dot.)

### ISSUE THREAD

**Issue by david-caroli** [Lusito/forget-me-not#79]
![screenshot from 2018-08-19 17-17-45](https://user-images.githubusercontent.com/18610453/44310322-7d934d80-a3d4-11e8-9e16-13c9b6f50c0d.png)  

**The Problem:**  
In the screen-shot are 3 examples of rules that the domain `www.reddit.com` matches, even though it shouldn't:  

- `*.t.co` (wrong top level domain `.co` and wrong domain `t`)  
- `www.reddit.co` (wrong top level domain `.co`)  
- `*.r.ddit.com` (`r.ddit` should not match `reddit`)  

**The likely cause:**  
The cause of this seems to be the conversion of the rule strings to regular expressions.  
The culprit function seems to be `getRegExForRule(rule: string)` in [settings.ts](https://github.com/Lusito/forget-me-not/blob/ea6bf7bb4630e59124f752d7b39a58c33c6d48bf/src/lib/settings.ts#L103).  

`getRegExForRule(rule: string)` correctly matches the start of the string using a `^`, but it should do the same for the end of the string. ([line 107](https://github.com/Lusito/forget-me-not/blob/ea6bf7bb4630e59124f752d7b39a58c33c6d48bf/src/lib/settings.ts#L107) and [line 110](https://github.com/Lusito/forget-me-not/blob/ea6bf7bb4630e59124f752d7b39a58c33c6d48bf/src/lib/settings.ts#L110))  

Additionally the function doesn't escape the characters from the rule when adding them to the regular expression. This leads to the dots in the rule not being escaped and treated as a special character. ([line 116](https://github.com/Lusito/forget-me-not/blob/ea6bf7bb4630e59124f752d7b39a58c33c6d48bf/src/lib/settings.ts#L116) and [line 117](https://github.com/Lusito/forget-me-not/blob/ea6bf7bb4630e59124f752d7b39a58c33c6d48bf/src/lib/settings.ts#L117))  

**Possibly a solution:**  
I have never used TypeScript and I don't use JavaScript often so take the following with a grain of salt.  

Change [line 117](https://github.com/Lusito/forget-me-not/blob/ea6bf7bb4630e59124f752d7b39a58c33c6d48bf/src/lib/settings.ts#L117) from `reParts.push(".");` to ``reParts.push("\\.");``.  

Before the return at [line 121](https://github.com/Lusito/forget-me-not/blob/ea6bf7bb4630e59124f752d7b39a58c33c6d48bf/src/lib/settings.ts#L121) add a line with `reParts.push("$");`.  
(see also [_RegEx Special Chars_](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp#Special_characters_meaning_in_regular_expressions))  
  
\-\-\-  
I hope the problem is reproducible and can be fixed. Thanks in advance!

**Comment by Lusito** [comment]
Thanks for the report! Not sure what I was thinking writing it this way.

There were other problems with this, so I've written a fix that addresses all of the issues.
I've also added unit-tests for this, so this won't happen in the future.
Please have a look at the above commit if you want to double check if there is anything I missed.

**Comment by david-caroli** [comment]
@Lusito The code looks good to me. Thank you for the quick fix and response!
