### ISSUE TITLE
Show list of cookies

### ISSUE THREAD

**Issue by Lusito** [Lusito/forget-me-not#9]
Offer possibility to browse cookies... a quick method might be to show this (on firefox):
chrome://browser/content/preferences/cookies.xul

**Comment by Lusito** [comment]
Opening chrome:// urls is forbidden, so this is no quick way to do this.
Instead, it would need to be re-implemented from scratch.

**Comment by Joel889** [comment]
I would love this, very much like Enhanced Cookie Manager that stopped working :(

**Comment by rmenessec** [comment]
[Cookiebro](https://addons.mozilla.org/en-US/firefox/addon/cookiebro/) does a fairly good job with this. I'd say either use Cookiebro or else maybe ask the developer if it's okay to borrow some Cookiebro code. (According to AMO, the license is "All rights reserved.")

If this feature is introduced, I'd like the ability to see DOM and IndexedDB storage as well; not necessarily in order to edit it, but just a way to see whether a given site—or maybe just the current site—is using DOM or IndexedDB storage. A tally of storage used per site in total IEC KiB / MiB would be nice, too.

**Comment by Lusito** [comment]
I think it would be more work to incorporate the code of another extension into mine than to write a cookie list myself.
Sadly, web-extensions doesn't offer a way to list Indexed Databases. And even from the website itself it is currently impossible to list databases. You need to know the name of the databases before you can access them.

Local Storage can not be listed by the web-extensions API either. It would be possible to see all items when the webpage is currently open, but I don't think it's worth the effort.
People can inspect the storage by using the developer tools already built into firefox:
https://developer.mozilla.org/en-US/docs/Tools/Storage_Inspector

Just press F12 and select the "Storage" tab while you're on the website you want to inspect.

**Comment by Joel889** [comment]
> Offer possibility to browse cookies... a quick method might be to show this (on firefox):
chrome://browser/content/preferences/cookies.xul

Looks like this method is broken in FF 64 :(

**Comment by ArchangeGabriel** [comment]
Having a way to list cookies (eventually see their content) and be able to create specific rules for them is exactly what I need from this extension. Currently I already have uMatrix to block and clean cookies, but what I would like is being able to allow/keep only specific cookies for a given website. :)

**Comment by Joel889** [comment]
> what I would like is being able to allow/keep only specific cookies for a given website. :)

This is already possible. Make it so that all cookies are deleted, then use the following as a whitelist of specific cookies to keep.

`cookie_name@*.domain.com`

**Comment by ArchangeGabriel** [comment]
Yes, but currently I cannot discover the cookies names from FMN.

**Comment by Joel889** [comment]
That's a good point, because Firefox no longer provides functionality to see cookie names, only whether cookies were set for a domain.

**Comment by bberberov** [comment]
@Joel889 Do you know which commit/bug made that "feature" in FF?

**Comment by Joel889** [comment]
No, but it was removed in FF 61.

**Comment by Lusito** [comment]
Draft Version (icon to the left of the trash icon):
![draft_icon](https://user-images.githubusercontent.com/1135267/53996855-57e45080-413a-11e9-8c99-5387124c606d.png)
![draft_browser](https://user-images.githubusercontent.com/1135267/53996860-5adf4100-413a-11e9-9c50-36822fc7baff.png)

**Comment by Lusito** [comment]
Solved
